export {default as Header} from "./Header/Header"; 
export {default as Main} from "./Main/Main";
export {default as Text} from "./Text/Text";
export {default as MainAbout} from "./MainAbout/MainAbout";
export {default as CardsAbout} from "./CardsAbout/CardsAbout";
export {default as MainContact} from "./MainContact/MainContact";
export {default as ContactFrom} from "./ContactFrom/ContactFrom";
export {default as Qustions} from "./Qustions/Qustions";
export {default as Footer} from "./Footer/Footer";